chore: try this

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -99,8 +99,11 @@ jobs:
               body: output
             })
       - name: Check Success
-        if:  (${{ success() }} || ${{ failure() }}) && (${{ steps.fmt.outcome }} == 'failure' || ${{ steps.plan.outcome }} == 'failure'))
+        if:  ${{ ( success()  ||  failure() ) && ( steps.fmt.outputs.exit_code  == 1 || steps.plan.outputs.exit_code == 1 )) }}
         run: |
+          echo steps.fmt.outcome ${{ steps.fmt.outcome }}
+          echo steps.plan.outcome ${{ steps.plan.outcome }}
+          echo "(${{ steps.fmt.outcome }} == failure || ${{ steps.plan.outcome }} == failure)"
           exit 1
 
   terraform-apply:
