fix: only pass if all succeed (#71)

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -32,6 +32,7 @@ env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
 jobs:
+
   terraform-plan-security-scan:
     if: github.ref != 'refs/heads/master'
     runs-on: ubuntu-latest
@@ -97,6 +98,13 @@ jobs:
               repo: context.repo.repo,
               body: output
             })
+      - name: Check Success
+        if:  ${{ ( success()  ||  failure() ) && ( steps.fmt.outputs.exit_code  == 1 || steps.plan.outputs.exit_code == 1 ) }}
+        run: |
+          echo steps.fmt.outcome ${{ steps.fmt.outcome }}
+          echo steps.plan.outcome ${{ steps.plan.outcome }}
+          echo "(${{ steps.fmt.outcome }} == failure || ${{ steps.plan.outcome }} == failure)"
+          exit 1
 
   terraform-apply:
     if: github.ref == 'refs/heads/master' && github.event_name == 'push'
